In [3]:
import numpy as np


very object contains the reference to a string, which is known as the docstring. In most cases, this docstring contains a quick and concise summary of the object and how to use it. Python has a built-in help() function that can help you access this information. This means that nearly any time you need more information, you can use help() to quickly find the information that you need.

In [30]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



IPython uses the ? character as a shorthand for accessing this documentation along with other relevant information. IPython is a command shell for interactive computing in multiple languages.

In [31]:
print?

You can reach another level of information by reading the source code of the object you’re interested in. Using a double question mark (??) allows you to access the source code.If the object in question is compiled in a language other than Python, using ?? will return the same information as ?.

In [52]:
In [4] print??

CREAE AN ARRAY

In [47]:
a = np.array([1, 2, 3])

Then you can obtain a lot of useful information (first details about a itself, followed by the docstring of ndarray of which a is an instance):

In [48]:
In [2]: a?

Print Single element of array

In [4]:
print (a[2])

3


Print whole Array

In [8]:
print (a)

[1 2 3]


create an Array with range of elements

In [33]:
b=np.arange(5)

In [34]:
print (b)

[0 1 2 3 4]


we can define an Array with defined range and interval space between elements

In [13]:
c=np.arange(2,56,3)
print (c)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53]


create an array with values that are spaced linearly in a specified interval

In [24]:
interval=np.linspace(0,300,num=6)
print(interval)

[  0.  60. 120. 180. 240. 300.]


define data type for elements other than default floating point data type

In [25]:
int_array=np.ones(6, dtype=np.int64)
print(int_array)

[1 1 1 1 1 1]


Sorting

In [30]:
score=np.array([56,21,0,102,3,89,40,5,23,99])
print(score)
sorted_score=np.sort(score)
print (sorted_score)

[ 56  21   0 102   3  89  40   5  23  99]
[  0   3   5  21  23  40  56  89  99 102]


Concatenation

In [35]:
con_array=np.concatenate((a,b))
print (con_array)

[1 2 3 0 1 2 3 4]


to find number of elements in an Array

In [39]:
con_array.size

8

We can Reshape an Array

In [41]:
new_array=con_array.reshape(4,2)
print (new_array)

[[1 2]
 [3 0]
 [1 2]
 [3 4]]


Slice of an Array

In [46]:
fifty_up = (score >= 50)
print(score[fifty_up])

[ 56 102  89  99]


In [53]:
between_50_and_100= score[(score > 49) & (score < 100)]
print(between_50_and_100)

[56 89 99]


create new array from an existing array

In [54]:
print(score)
new_array=score[2:6]
print(new_array)

[ 56  21   0 102   3  89  40   5  23  99]
[  0 102   3  89]


Stacking the Arrays vertically by vstack & horizantally by hstack

In [57]:
arr1=np.array([[1,1],[2,2]])
arr2=np.array([[3,3],[4,4]])
np.vstack((arr1,arr2))
np.hstack((arr1,arr2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

reshape an array into three equal size arrays

In [63]:
x = np.arange(1, 25).reshape(3,8)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

Split an Array into 4 equaliy shaped arrays

In [72]:
np.hsplit(x,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24]])]

Creating VIEW, modifying data in a view also modifies the original array!

In [83]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[0, :]
b

array([1, 2, 3, 4])

In [90]:
b[0] = 99
b

array([99,  2,  3,  4])

In [88]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

copy method will make a complete copy of the array and its data (a deep copy)

In [92]:
a2 = a.copy()
a2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
a2[0]=101
a2

array([[101, 101, 101, 101],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [95]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

we can Add, multiply,subtract and divide two or more arrays

In [4]:
array1=np.array([4,5])
array2=np.array([2,3])
array3=np.array([2,2])
array1+array2+array3

array([ 8, 10])

In [108]:
array1-array2+array3

array([4, 4])

In [107]:
array1*array2*array3

array([16, 30])

In [110]:
array1*array2/array3

array([4. , 7.5])

You can also find max,min and sum of an array

In [6]:
array1.max()

5

In [7]:
array1.min()

4

In [8]:
array1.sum()

9

finding unique items their indexes and occurance counts and in Array

In [39]:
f= np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(f)
print(unique_values)


[11 12 13 14 15 16 17 18 19 20]


In [40]:
nique_values, indices_list = np.unique(f, return_index=True)
print(indices_list)


[ 0  2  3  4  5  6  7 12 13 14]


In [41]:
unique_values, occurrence_count = np.unique(f, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


Reshape and transpose as per your required input

In [42]:
f.reshape(5, 3)

array([[11, 11, 12],
       [13, 14, 15],
       [16, 17, 12],
       [13, 11, 14],
       [18, 19, 20]])

In [43]:
f.transpose()

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

reverse an array

In [44]:
reversed_arr = np.flip(f)

In [45]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [20 19 18 14 11 13 12 17 16 15 14 13 12 11 11]


In [17]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [18]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [19]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [20]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [21]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [22]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays.
ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.


In [23]:
g = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [24]:
a1 = g.flatten()
>>> a1[0] = 99
>>> print(g) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
a2 = g.ravel()
a2[0] = 98
print(g)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
